# Generated by Django 5.0.6 on 2024-07-02 12:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restourant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(default=None, max_length=1000, verbose_name='Description')),
                ('stars', models.IntegerField(default=None, verbose_name='Stars')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_created', models.DateField(default=datetime.datetime(2024, 7, 2, 12, 56, 55, 494500), verbose_name='Day of creation')),
                ('description', models.CharField(default=None, max_length=1000, verbose_name='Description')),
                ('restourant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_api.restourant')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_vote', models.DateField(default=datetime.datetime(2024, 7, 2, 12, 56, 55, 494800), verbose_name='Day of vote')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_api.menu', verbose_name='Menu of the day')),
            ],
        ),
    ]
