# Generated by Django 5.0.6 on 2024-07-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0003_alter_menu_day_created_alter_vote_day_of_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(default=0, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='restourant',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='Stars'),
        ),
    ]
