# Generated by Django 5.0.6 on 2024-07-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0004_alter_menu_description_alter_restourant_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restourant',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
