# Generated by Django 5.0.6 on 2024-07-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0005_alter_restourant_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restourant',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='restourant',
            new_name='restaurant',
        ),
    ]
