# Generated by Django 5.0.6 on 2024-07-02 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0006_rename_restourant_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='day_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Day of creation'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='day_of_vote',
            field=models.DateField(default=datetime.date.today, verbose_name='Day of vote'),
        ),
    ]
