# Generated by Django 5.0.6 on 2024-07-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0008_alter_vote_user_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('restaurant', 'day_created')},
        ),
    ]
